AWSTemplateFormatVersion: 2010-09-09
Description: A simple EC2 instance
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0bbed01be11b34b90
      InstanceType: t2.micro
      KeyName: cfn-key-1
